import { notFound } from "next/navigation";
import Link from "next/link";
import { Activity, Check, X, Github, Sparkles, Terminal } from "lucide-react";
import type { Metadata } from "next";

interface CompetitorData {
  name: string;
  key: string;
  tagline: string;
  description: string;
  setupTime: string;
  setupTimeAlt: string;
  pricing: string;
  pricingAlt: string;
  aiFeatures: string;
  aiFeaturesAlt: string;
  piiProtection: string;
  piiProtectionAlt: string;
  otlp: string;
  otlpAlt: string;
  highlights: string[];
}

const COMPETITORS: Record<string, CompetitorData> = {
  datadog: {
    name: "Datadog",
    key: "datadog",
    tagline:
      "Stop paying massive, unpredictable bills per host and host metric.",
    description:
      "Datadog is a great legacy observability suite, but its complex pricing models, seat-based metrics, and high billing surprise factors make it highly restrictive for fast-moving startups. ObservabilityOS offers a flat $29/mo plan with AI-powered root-cause answers instead of raw graphs.",
    setupTime: "1 Minute (Single SDK/Sidecar)",
    setupTimeAlt: "Days of YAML configuration and agent installation",
    pricing: "Flat $29/mo (No seat/host limits)",
    pricingAlt:
      "Complex matrix per host, metric, and logs custom retention rules",
    aiFeatures: "Automated GPT-4/Claude post-mortems in under 10 seconds",
    aiFeaturesAlt:
      "Basic anomaly detection dashboards without plain-text explanations",
    piiProtection: "Local SDK scrubbing (scrubber.ts)",
    piiProtectionAlt: "Sent blindly to cloud servers (compliance hazard)",
    otlp: "Native HTTP OTLP JSON ingest endpoint",
    otlpAlt: "Requires agent-side exporter routing configuration",
    highlights: [
      "Eliminate unpredictable bills: Pay $29/mo instead of fluctuating $1,000+ monthly fees.",
      "Instant explanations: Instead of manual timeline graphs correlation, get a written summary of what commit broke production.",
      "100% compliant data pipelines: Sensitive client data is automatically redacted on your own machine before leaving the local sandbox.",
    ],
  },
  "new-relic": {
    name: "New Relic",
    key: "new-relic",
    tagline:
      "Get clear billing and actual AI-driven answers instead of graph grids.",
    description:
      "New Relic charges heavily per developer seat, making it expensive to share telemetry data across your engineering team. ObservabilityOS encourages developer collaboration with flat subscription models and structured Slack post-mortems.",
    setupTime: "1 Minute (Single SDK/Sidecar)",
    setupTimeAlt: "Proprietary agents setup and configuration debugging",
    pricing: "Flat $29/mo (No seat/host limits)",
    pricingAlt: "Expensive per-user fees and volume ingest overage bills",
    aiFeatures: "Automated GPT-4/Claude post-mortems in under 10 seconds",
    aiFeaturesAlt: "Separate add-on products and basic regression alerting",
    piiProtection: "Local SDK scrubbing (scrubber.ts)",
    piiProtectionAlt: "Custom setup required inside dashboard UI filters",
    otlp: "Native HTTP OTLP JSON ingest endpoint",
    otlpAlt: "Supported but requires exporting agent overrides",
    highlights: [
      "No developer tax: Add your entire product team to ObservabilityOS without paying per user seat.",
      "Zero-noise alerting: Standard deviation rolling Z-scores filter out noisy metrics, saving your engineers from alert fatigue.",
      "Open telemetry compliance: Standard OTLP protocol support lets you migrate your collectors in minutes.",
    ],
  },
  grafana: {
    name: "Grafana",
    key: "grafana",
    tagline:
      "Replace complex dashboard tweaking with automated system intelligence.",
    description:
      "Grafana is the industry standard for custom charts, but building, maintaining, and debugging those dashboard grids takes hours of development time. ObservabilityOS generates microservice layouts and charts automatically from log schema types.",
    setupTime: "1 Minute (Single SDK/Sidecar)",
    setupTimeAlt:
      "Configuring Prometheus, Promtail, Loki, and custom dashboards",
    pricing: "Flat $29/mo (No seat/host limits)",
    pricingAlt:
      "Free open-source but high hosting/maintenance costs; Cloud gets expensive quickly",
    aiFeatures: "Automated GPT-4/Claude post-mortems in under 10 seconds",
    aiFeaturesAlt: "None (Manual dashboard timeline review required)",
    piiProtection: "Local SDK scrubbing (scrubber.ts)",
    piiProtectionAlt: "Must configure ingestion-level regex pipelines manually",
    otlp: "Native HTTP OTLP JSON ingest endpoint",
    otlpAlt: "Requires custom agent/pipeline configurations",
    highlights: [
      "No dashboard maintenance: Autogenerated system layouts replace manual queries and YAML configs.",
      "Understand what broke: Don't spend hours searching through log spikes; read the root cause in plain English.",
      "Local security defaults: Safe data scrubbing prevents logging client credentials into Mongoose/Atlas clusters.",
    ],
  },
  sentry: {
    name: "Sentry",
    key: "sentry",
    tagline:
      "Log analytics and AI incident correlation combined in one platform.",
    description:
      "Sentry is excellent for frontend stack stack-traces, but lacks complete system-wide log analytics and OpenTelemetry structure. ObservabilityOS acts as both a system log database and an incident correlator.",
    setupTime: "1 Minute (Single SDK/Sidecar)",
    setupTimeAlt:
      "Different configurations for backend log engines and client traces",
    pricing: "Flat $29/mo (No seat/host limits)",
    pricingAlt: "Charged per error event and transaction volume scales",
    aiFeatures: "Automated GPT-4/Claude post-mortems in under 10 seconds",
    aiFeaturesAlt: "Basic stack trace summaries without deployment correlation",
    piiProtection: "Local SDK scrubbing (scrubber.ts)",
    piiProtectionAlt: "Dashboard-side filtering with default server rules",
    otlp: "Native HTTP OTLP JSON ingest endpoint",
    otlpAlt: "Mainly focused on proprietary trace formats",
    highlights: [
      "Unified log data: Query all your server output lines, API metrics, and trace telemetry from a single interface.",
      "GitHub commit integration: Instantly maps deployment commit diffs to the errors they introduced.",
      "Flat cost safety: Fixed cost prevents unexpected log spikes from producing massive, surprise monthly bills.",
    ],
  },
  "better-stack": {
    name: "Better Stack",
    key: "better-stack",
    tagline: "AI-powered post-mortems that explain the why, not just the when.",
    description:
      "Better Stack offers fast log queries and basic Uptime checking. However, they lack AI-native diagnostics to automatically pinpoint developer commit failures. ObservabilityOS couples log search with GPT-4 and Claude summaries.",
    setupTime: "1 Minute (Single SDK/Sidecar)",
    setupTimeAlt: "Custom fluentd configurations and vector routing setups",
    pricing: "Flat $29/mo (No seat/host limits)",
    pricingAlt:
      "Tier-based pricing that restricts team seats and query history length",
    aiFeatures: "Automated GPT-4/Claude post-mortems in under 10 seconds",
    aiFeaturesAlt: "None (Provides raw logs but no automated explanations)",
    piiProtection: "Local SDK scrubbing (scrubber.ts)",
    piiProtectionAlt: "Must define cloud-side scrubbing regexes manually",
    otlp: "Native HTTP OTLP JSON ingest endpoint",
    otlpAlt: "Requires custom exporter forwarding configs",
    highlights: [
      "AI Diagnostic power: Lower MTTR from hours to under 30 seconds with automated root-cause reports.",
      "Local SDK safety: Redact secrets before they hit your external cloud database pipelines.",
      "Predictable startup budget: Support developer side-projects and enterprise workloads without usage-based billing traps.",
    ],
  },
};

export async function generateStaticParams() {
  return Object.keys(COMPETITORS).map((competitor) => ({
    competitor,
  }));
}

interface PageProps {
  params: Promise<{
    competitor: string;
  }>;
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const resolvedParams = await params;
  const comp = COMPETITORS[resolvedParams.competitor];

  if (!comp) {
    return { title: "Not Found" };
  }

  const title = `ObservabilityOS vs ${comp.name} — AI-Native Telemetry Comparison`;
  const description = `Compare ObservabilityOS and ${comp.name}. Learn why engineering teams choose ObservabilityOS for flat-rate pricing, local PII scrubbing, and AI root cause analysis.`;
  const baseUrl =
    process.env.NEXT_PUBLIC_APP_URL || "https://observabilityos.com";

  return {
    title,
    description,
    alternates: {
      canonical: `${baseUrl}/vs/${comp.key}`,
    },
    openGraph: {
      title,
      description,
      url: `${baseUrl}/vs/${comp.key}`,
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

export default async function CompetitorPage({ params }: PageProps) {
  const resolvedParams = await params;
  const comp = COMPETITORS[resolvedParams.competitor];

  if (!comp) {
    notFound();
  }

  const baseUrl =
    process.env.NEXT_PUBLIC_APP_URL || "https://observabilityos.com";
  const webPageSchema = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: `ObservabilityOS vs ${comp.name}`,
    description: comp.description,
    url: `${baseUrl}/vs/${comp.key}`,
    breadcrumb: {
      "@type": "BreadcrumbList",
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: baseUrl,
        },
        {
          "@type": "ListItem",
          position: 2,
          name: `Compare ${comp.name}`,
          item: `${baseUrl}/vs/${comp.key}`,
        },
      ],
    },
  };

  return (
    <div className="flex flex-col min-h-screen bg-slate-950 text-slate-100 selection:bg-indigo-500 selection:text-white font-sans overflow-x-hidden relative">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageSchema) }}
      />

      {/* Background patterns */}
      <div className="absolute top-0 left-1/4 w-120 h-120 bg-indigo-500/5 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-120 h-120 bg-purple-500/5 rounded-full blur-[120px] pointer-events-none" />

      {/* Header */}
      <header className="sticky top-0 z-50 backdrop-blur-md bg-slate-950/75 border-b border-slate-900/80">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link
            href="/"
            className="flex items-center gap-2.5 hover:opacity-90 transition-opacity"
          >
            <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center">
              <Activity className="w-4 h-4 text-white" />
            </div>
            <span className="font-semibold text-lg tracking-tight bg-linear-to-r from-white to-slate-400 bg-clip-text text-transparent">
              ObservabilityOS
            </span>
          </Link>
          <div className="flex items-center gap-4">
            <a
              href="https://github.com/Vaibhav-Singh2/ObservabilityOS"
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs font-semibold text-slate-400 hover:text-slate-200 transition-colors flex items-center gap-1.5"
            >
              <Github className="w-4 h-4" />
              GitHub
            </a>
            <Link
              href="/"
              className="bg-indigo-600 hover:bg-indigo-500 text-white px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all"
            >
              Go to App
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <main className="flex-1 w-full max-w-5xl mx-auto px-6 py-16">
        <section className="text-center mb-16 max-w-3xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-[10px] font-bold uppercase tracking-wider mb-6 font-mono">
            ObservabilityOS vs {comp.name}
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight mb-6 bg-linear-to-b from-white to-slate-450 bg-clip-text text-transparent">
            {comp.tagline}
          </h1>
          <p className="text-slate-400 text-sm sm:text-base leading-relaxed">
            {comp.description}
          </p>
        </section>

        {/* Feature Grid / Side-by-Side Comparison */}
        <section className="mb-16">
          <h2 className="text-xl sm:text-2xl font-extrabold mb-8 text-center text-slate-200">
            Side-by-Side Comparison
          </h2>
          <div className="w-full overflow-x-auto rounded-2xl border border-slate-900 bg-slate-950/40">
            <table className="w-full min-w-150 text-left border-collapse text-sm">
              <thead>
                <tr className="border-b border-slate-900 bg-slate-900/20 text-slate-400 font-semibold font-mono text-xs uppercase">
                  <th className="p-5">Feature</th>
                  <th className="p-5 text-indigo-400">ObservabilityOS</th>
                  <th className="p-5">{comp.name}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-900 text-slate-350">
                <tr>
                  <td className="p-5 font-semibold text-slate-200">
                    Billing Setup
                  </td>
                  <td className="p-5 text-indigo-400 font-semibold">
                    {comp.pricing}
                  </td>
                  <td className="p-5 text-slate-500">{comp.pricingAlt}</td>
                </tr>
                <tr>
                  <td className="p-5 font-semibold text-slate-200">
                    Setup Complexity
                  </td>
                  <td className="p-5 text-emerald-400 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />{" "}
                    {comp.setupTime}
                  </td>
                  <td className="p-5 text-slate-500 flex items-center gap-2">
                    <X className="w-4 h-4 text-red-500 shrink-0" />{" "}
                    {comp.setupTimeAlt}
                  </td>
                </tr>
                <tr>
                  <td className="p-5 font-semibold text-slate-200">
                    AI incident root cause
                  </td>
                  <td className="p-5 text-emerald-400 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />{" "}
                    {comp.aiFeatures}
                  </td>
                  <td className="p-5 text-slate-500 flex items-center gap-2">
                    <X className="w-4 h-4 text-red-500 shrink-0" />{" "}
                    {comp.aiFeaturesAlt}
                  </td>
                </tr>
                <tr>
                  <td className="p-5 font-semibold text-slate-200">
                    PII Data Scrubbing
                  </td>
                  <td className="p-5 text-emerald-400 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />{" "}
                    {comp.piiProtection}
                  </td>
                  <td className="p-5 text-slate-500 flex items-center gap-2">
                    <X className="w-4 h-4 text-red-500 shrink-0" />{" "}
                    {comp.piiProtectionAlt}
                  </td>
                </tr>
                <tr>
                  <td className="p-5 font-semibold text-slate-200">
                    OpenTelemetry compliance
                  </td>
                  <td className="p-5 text-emerald-400 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-400 shrink-0" />{" "}
                    {comp.otlp}
                  </td>
                  <td className="p-5 text-slate-500">{comp.otlpAlt}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* Why Choose ObservabilityOS Section */}
        <section className="mb-20">
          <h2 className="text-xl sm:text-2xl font-extrabold mb-8 text-center text-slate-200">
            Why engineers prefer ObservabilityOS
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {comp.highlights.map((highlight, idx) => {
              const parts = highlight.split(":");
              const title = parts[0];
              const desc = parts.slice(1).join(":");
              return (
                <div
                  key={idx}
                  className="bg-slate-900/30 border border-slate-900 p-6 rounded-2xl"
                >
                  <div className="w-8 h-8 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center mb-4 text-indigo-400">
                    <Sparkles className="w-4 h-4" />
                  </div>
                  <h3 className="font-bold text-slate-200 mb-2">{title}</h3>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    {desc}
                  </p>
                </div>
              );
            })}
          </div>
        </section>

        {/* Call To Action */}
        <section className="bg-radial from-slate-900/60 to-slate-950 border border-slate-900 rounded-3xl p-8 sm:p-12 text-center relative overflow-hidden">
          <div className="absolute -top-20 -left-20 w-80 h-80 bg-indigo-500/5 rounded-full blur-[100px] pointer-events-none" />
          <h2 className="text-2xl sm:text-3xl font-extrabold mb-4 text-white">
            Ready to experience AI-Native Observability?
          </h2>
          <p className="text-slate-400 text-sm max-w-xl mx-auto mb-8 leading-relaxed">
            Get started for free. Deploy our zero-dependency logger SDK or
            connect your OpenTelemetry pipeline in minutes.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 w-full sm:w-auto">
            <Link
              href="/"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-white hover:bg-slate-100 text-slate-950 font-bold h-11 px-6 rounded-xl transition-all"
            >
              <Github className="w-4 h-4" />
              Sign Up with GitHub
            </Link>
            <Link
              href="https://docs.observabilityos.com"
              className="w-full sm:w-auto inline-flex items-center justify-center gap-2 bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-200 h-11 px-6 rounded-xl transition-all font-semibold"
            >
              <Terminal className="w-4 h-4 text-indigo-400" />
              Read Setup Docs
            </Link>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-900 bg-slate-950 py-8 text-center text-xs text-slate-600 font-mono">
        <div>
          &copy; {new Date().getFullYear()} ObservabilityOS. All rights
          reserved. Open Source.
        </div>
      </footer>
    </div>
  );
}
